name: macOS Cloud Remote Environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Setup Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          brew install tailscale
          sudo tailscaled --state=mem: &
          sleep 5
          sudo tailscale up --authkey=$TAILSCALE_AUTHKEY --hostname=github-mac-runner

      - name: Setup Tmate SSH & Web Terminal Access
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
